name: RewriteTests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test if htaccess files in current directory does multiple wanted redirects
      uses: madewithlove/htaccess-cli-github-action@multiple
      with:
        url: https://w3id.org/gpo/GPO_01cd2578_8730_4ac9_a555_9112728ea939
        expected-url: https://onto-wiki.eu/wiki/Special:AskResolver?iri=https://w3id.org/gpo/GPO_01cd2578_8730_4ac9_a555_9112728ea939
        path: ./gpo/
